{# ecliptic: work -#}
{% extends "Snakefile.base" %}

{% block settings %}
{% include "Snakefile.settings" %}
{% endblock %}

{% block rules %}

BEGINMARK = '.time.begin'
FINISHMARK = '.time.finish'

all_targets = []
targets = all_targets.extend

rule _dummy:
    shell: 'echo "==>>> Invoke snakemake with target \`all\`."'

{% include "Snakefile.10.fundamental" %}
{% include "Snakefile.20.quantitation" %}
{% include "Snakefile.30.erroranalysis" %}
{% include "Snakefile.40.piranha" %}
{% include "Snakefile.100.stats" %}
{% include "Snakefile.200.report" %}

rule _beginmark:
    output: BEGINMARK
    run:
        print(time.time(), file=open(output[0], 'w'))

rule all:
    input: all_targets
    run:
        pass

{% endblock %}
